# Generated by Django 5.0.8 on 2024-09-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
